-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 19:59:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `warranty` TINYINT NOT NULL,
  `equipmentWithLCDDispaly` TINYINT NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workers` (
  `idworkers` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `secondName` VARCHAR(45) NULL,
  `birthDate` DATE NOT NULL,
  `sex` TINYINT NOT NULL,
  PRIMARY KEY (`idworkers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`offices` (
  `idoffices` INT NOT NULL AUTO_INCREMENT,
  `officescol` VARCHAR(45) NOT NULL,
  `casing` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idoffices`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`info` (
  `idinfo` INT NOT NULL,
  `nameOfModel` VARCHAR(45) NOT NULL,
  `category_category_id` INT NOT NULL,
  PRIMARY KEY (`idinfo`),
  INDEX `fk_info_category1_idx` (`category_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_info_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipments` (
  `idequipments` INT NOT NULL,
  `equipmentscol` VARCHAR(45) NOT NULL,
  `category_category_id` INT NOT NULL,
  `havingAParts` TINYINT NOT NULL,
  `info_idinfo` INT NOT NULL,
  `serialNumber` INT NOT NULL,
  PRIMARY KEY (`idequipments`),
  INDEX `fk_equipments_category_idx` (`category_category_id` ASC) VISIBLE,
  INDEX `fk_equipments_info1_idx` (`info_idinfo` ASC) VISIBLE,
  CONSTRAINT `fk_equipments_category`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipments_info1`
    FOREIGN KEY (`info_idinfo`)
    REFERENCES `mydb`.`info` (`idinfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`history` (
  `idmainTable` INT NOT NULL,
  `idWorker` INT NOT NULL,
  `idOffice` INT NOT NULL,
  `idEquipmets` INT NOT NULL,
  `offices_idoffices` INT NOT NULL,
  `equipments_idequipments` INT NOT NULL,
  `workers_idworkers` INT NOT NULL,
  `dateOfAddingToTheWorkWorker` DATE NOT NULL,
  `dateOfDeletefromTheWorkWorker` DATE NOT NULL,
  `dateOfAddingEquipment` DATE NOT NULL,
  `dateOfDeletingEquipment` DATE NULL,
  `dateOfChangingWorkerWhoRelatesAsEquipment` DATE NULL,
  `dateOfCrashingEquipment` DATE NULL,
  PRIMARY KEY (`idmainTable`),
  INDEX `fk_mainTable_offices1_idx` (`offices_idoffices` ASC) VISIBLE,
  INDEX `fk_mainTable_equipments1_idx` (`equipments_idequipments` ASC) VISIBLE,
  INDEX `fk_mainTable_workers1_idx` (`workers_idworkers` ASC) VISIBLE,
  CONSTRAINT `fk_mainTable_offices1`
    FOREIGN KEY (`offices_idoffices`)
    REFERENCES `mydb`.`offices` (`idoffices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mainTable_equipments1`
    FOREIGN KEY (`equipments_idequipments`)
    REFERENCES `mydb`.`equipments` (`idequipments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mainTable_workers1`
    FOREIGN KEY (`workers_idworkers`)
    REFERENCES `mydb`.`workers` (`idworkers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`category` (`category_id`, `name`, `warranty`, `equipmentWithLCDDispaly`) VALUES (1, 'opticalDevices', true, false);
INSERT INTO `mydb`.`category` (`category_id`, `name`, `warranty`, `equipmentWithLCDDispaly`) VALUES (2, 'computers', false, true);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`workers`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`workers` (`idworkers`, `name`, `surname`, `secondName`, `birthDate`, `sex`) VALUES (1, 'Alex', 'Grygoriew', 'Smith', '10.10.1990', male);
INSERT INTO `mydb`.`workers` (`idworkers`, `name`, `surname`, `secondName`, `birthDate`, `sex`) VALUES (2, 'Anna', 'Kozulyak', 'Ivanivna', '13.11.1992', female);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`offices`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`offices` (`idoffices`, `officescol`, `casing`) VALUES (1, 'mathAuditory', '3');
INSERT INTO `mydb`.`offices` (`idoffices`, `officescol`, `casing`) VALUES (2, 'decanat', '3');
INSERT INTO `mydb`.`offices` (`idoffices`, `officescol`, `casing`) VALUES (3, 'physicLabolatory', '2');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`info`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`info` (`idinfo`, `nameOfModel`, `category_category_id`) VALUES (1, 'Lenovo', 34);
INSERT INTO `mydb`.`info` (`idinfo`, `nameOfModel`, `category_category_id`) VALUES (2, 'Asus', 12);
INSERT INTO `mydb`.`info` (`idinfo`, `nameOfModel`, `category_category_id`) VALUES (3, 'Panasonic', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`equipments`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`equipments` (`idequipments`, `equipmentscol`, `category_category_id`, `havingAParts`, `info_idinfo`, `serialNumber`) VALUES (1, 'notebook', computers, true, 234, 24324232);
INSERT INTO `mydb`.`equipments` (`idequipments`, `equipmentscol`, `category_category_id`, `havingAParts`, `info_idinfo`, `serialNumber`) VALUES (2, 'microscope', optical devices, false, 231, 32325345);
INSERT INTO `mydb`.`equipments` (`idequipments`, `equipmentscol`, `category_category_id`, `havingAParts`, `info_idinfo`, `serialNumber`) VALUES (3, 'laser pointer', optical devices, false, 34, 45463645);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`history`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`history` (`idmainTable`, `idWorker`, `idOffice`, `idEquipmets`, `offices_idoffices`, `equipments_idequipments`, `workers_idworkers`, `dateOfAddingToTheWorkWorker`, `dateOfDeletefromTheWorkWorker`, `dateOfAddingEquipment`, `dateOfDeletingEquipment`, `dateOfChangingWorkerWhoRelatesAsEquipment`, `dateOfCrashingEquipment`) VALUES (1, 3, 2, 34, 2, 23, 12, '7.7.2010', DEFAULT, '01.1.2014', NULL, NULL, NULL);
INSERT INTO `mydb`.`history` (`idmainTable`, `idWorker`, `idOffice`, `idEquipmets`, `offices_idoffices`, `equipments_idequipments`, `workers_idworkers`, `dateOfAddingToTheWorkWorker`, `dateOfDeletefromTheWorkWorker`, `dateOfAddingEquipment`, `dateOfDeletingEquipment`, `dateOfChangingWorkerWhoRelatesAsEquipment`, `dateOfCrashingEquipment`) VALUES (2, 4, 1, 21, 1, 21, 23, '05.05.2016', DEFAULT, '03.07.2015', NULL, NULL, NULL);
INSERT INTO `mydb`.`history` (`idmainTable`, `idWorker`, `idOffice`, `idEquipmets`, `offices_idoffices`, `equipments_idequipments`, `workers_idworkers`, `dateOfAddingToTheWorkWorker`, `dateOfDeletefromTheWorkWorker`, `dateOfAddingEquipment`, `dateOfDeletingEquipment`, `dateOfChangingWorkerWhoRelatesAsEquipment`, `dateOfCrashingEquipment`) VALUES (3, 2, 1, 23, 3, 34, 21, '07.11.2018', '01.09.2019', '03.02.2019', NULL, NULL, NULL);

COMMIT;

